# Generated by Django 4.2.3 on 2023-08-01 17:15

from django.db import migrations, models
import user_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='alergies',
            field=models.JSONField(default=user_api.models.AppUser.default_json),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='prefrences',
            field=models.JSONField(default=user_api.models.AppUser.default_json),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='restrictions',
            field=models.JSONField(default=user_api.models.AppUser.default_json),
        ),
    ]
