# Generated by Django 4.2.3 on 2023-08-01 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='pantry',
            name='staples',
        ),
        migrations.AlterField(
            model_name='pantry',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True, verbose_name='Last Updated On'),
        ),
    ]
