# Generated by Django 4.2.3 on 2023-08-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_recipe_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='nutritional_data',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
    ]
