# Generated by Django 4.2.3 on 2023-07-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_user_alergies_alter_user_prefrences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prefrences',
            field=models.JSONField(default={}),
        ),
    ]
