# Generated by Django 4.2.3 on 2023-07-31 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_alter_user_alergies_alter_user_prefrences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantry',
            name='staples',
        ),
        migrations.AlterField(
            model_name='pantry',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True, verbose_name='Last Updated On'),
        ),
    ]
