# Generated by Django 4.2.3 on 2023-07-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_remove_pantry_staples_alter_pantry_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='nutritional_data',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
    ]
